/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chessnut_EasyLink */

#ifndef _Included_com_chessnut_EasyLink
#define _Included_com_chessnut_EasyLink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chessnut_EasyLink
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chessnut_EasyLink_version
  (JNIEnv *, jclass);

/*
 * Class:     com_chessnut_EasyLink
 * Method:    connect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_chessnut_EasyLink_connect
  (JNIEnv *, jclass);

/*
 * Class:     com_chessnut_EasyLink
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_chessnut_EasyLink_disconnect
  (JNIEnv *, jclass);

/*
 * Class:     com_chessnut_EasyLink
 * Method:    switchRealTimeMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_chessnut_EasyLink_switchRealTimeMode
  (JNIEnv *, jclass);

/*
 * Class:     com_chessnut_EasyLink
 * Method:    switchUploadMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_chessnut_EasyLink_switchUploadMode
  (JNIEnv *, jclass);

/*
 * Class:     com_chessnut_EasyLink
 * Method:    setRealtimeCallback
 * Signature: (Lcom/chessnut/EasyLink/IRealTimeCallback;)V
 */
JNIEXPORT void JNICALL Java_com_chessnut_EasyLink_setRealtimeCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_chessnut_EasyLink
 * Method:    beep
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_chessnut_EasyLink_beep
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_chessnut_EasyLink
 * Method:    led
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_chessnut_EasyLink_led
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_chessnut_EasyLink
 * Method:    getMcuVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chessnut_EasyLink_getMcuVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_chessnut_EasyLink
 * Method:    getBleVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chessnut_EasyLink_getBleVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_chessnut_EasyLink
 * Method:    getBattery
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_chessnut_EasyLink_getBattery
  (JNIEnv *, jclass);

/*
 * Class:     com_chessnut_EasyLink
 * Method:    getFileCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_chessnut_EasyLink_getFileCount
  (JNIEnv *, jclass);

/*
 * Class:     com_chessnut_EasyLink
 * Method:    getFile
 * Signature: (Z)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_chessnut_EasyLink_getFile
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
