name: easylink

on: [push]

jobs:
  build_easylink:
    name: build_easylink

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: make build directory
        run: mkdir build

      - name: build
        working-directory: build
        run: |
          cmake .. -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build . --config Release

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: easylink-windows
          path: |
            ./build/*.dll
            ./build/*.lib
            ./easy_link_c.h
