name: easylink

on: [push]

jobs:
  build_easylink:
    name: build_easylink

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: make build directory
        run: mkdir build

      - name: show versions of cmake and clang
        run: |
          cmake --version
          clang --version
          clang++ --version

      - name: show cmake help
        run: cmake --help

      - name: build
        run: |
          cmake -B build/ -S . -G "Ninja Multi-Config" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build build/ --config Release --target all

      - name: show dir tree
        run: ls -R

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: easylink-windows
          path: |
            ./build/x64-Release/sdk/*.dll
            ./build/x64-Release/sdk/*.lib
            ./sdk/easy_link_c.h
