name: easylink

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_easylink:
    name: build_easylink

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create build directory
        run: mkdir build

      - name: Install ninja (for use with cmake)
        run: |
          choco install ninja -y
          ninja --version

      - name: Show versions of cmake and clang
        run: |
          cmake --version
          clang --version
          clang++ --version

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -S . -G "Ninja Multi-Config" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Compile
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all

      - name: Show dir tree
        run: ls -R

      - uses: actions/upload-artifact@v3.1.3
        with:
          name: easylink-windows-x64
          path: |
            ./build/sdk/${{env.BUILD_TYPE}}/*.dll
            ./build/sdk/${{env.BUILD_TYPE}}/*.lib
            ./sdk/easy_link_c.h
